" Acronyms
abbr ctan \gls{ctan}
abbr fi \gls{fi}
abbr mu \gls{mu}
abbr tex \gls{tex}
abbr latex \gls{latex}
abbr csplain \gls{csplain}
abbr cuni \gls{cuni}
abbr cvut \gls{cvut}
abbr opmac \gls{opmac}
abbr docclass \gls{docclass}
abbr makefile \gls{makefile}
abbr cslatex \gls{cslatex}
abbr cmfonts \gls{cmfonts}
abbr ecfonts \gls{ecfonts}
abbr csfonts \gls{csfonts}
abbr lmfonts \gls{lmfonts}
abbr texpackage \gls{texpackage}
abbr ltxpackage \gls{ltxpackage}
